// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibraryProject.Models;

public partial class Mountain
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Height { get; set; }

    public string Location { get; set; }

    public DateTime? AscentDate { get; set; }

    public bool IsClimbed { get; set; }
}